const cardArray = [
  {
    id: 1,
    name: "Halyna Vasylytsia",
    category: "portret",
    image: "../../../images/v-1.jpg",
  },

  {
    id: 2,
    name: "Halyna Vasylytsia",
    category: "portret",
    image: "../../../images/v-2.jpg",
  },
  {
    id: 3,
    name: "Halyna Vasylytsia",
    category: "portret",
    image: "../../../images/v-3.jpg",
  },
  {
    id: 4,
    name: "Halyna Vasylytsia",
    category: "portret",
    image: "../../../images/v-4.jpg",
  },
  {
    id: 5,
    name: "Halyna Vasylytsia",
    category: "portret",
    image: "../../../images/v-5.jpg",
  },
  {
    id: 6,
    name: "Halyna Vasylytsia",
    category: "portret",
    image: "../../../images/v-6.jpg",
  },
  {
    id: 7,
    name: "Halyna Vasylytsia",
    category: "portret",
    image: "../../../images/v-7.jpg",
  },
  {
    id: 8,
    name: "Halyna Vasylytsia",
    category: "portret",
    image: "../../../images/v-8.jpg",
  },
  {
    id: 9,
    name: "Halyna Vasylytsia",
    category: "portret",
    image: "../../../images/v-9.jpg",
  },
  {
    id: 10,
    name: "Hrystyna Kulyavych",
    category: "portret",
    image: "../../../images/hrystyna-1.jpg",
  },
  {
    id: 11,
    name: "Hrystyna Kulyavych",
    category: "family",
    image: "../../../images/hrystyna-2.jpg",
  },
  {
    id: 12,
    name: "Hrystyna Kulyavych",
    category: "portret",
    image: "../../../images/hrystyna-3.jpg",
  },
  {
    id: 13,
    name: "Hrystyna Kulyavych",
    category: "family",
    image: "../../../images/hrystyna-4.jpg",
  },
  {
    id: 14,
    name: "Hrystyna Kulyavych",
    category: "family",
    image: "../../../images/hrystyna-5.jpg",
  },
  {
    id: 15,
    name: "Hrystyna Kulyavych",
    category: "family",
    image: "../../../images/hrystyna-6.jpg",
  },
  {
    id: 16,
    name: "Hrystyna Kulyavych",
    category: "family",
    image: "../../../images/hrystyna-7.jpg",
  },
  {
    id: 17,
    name: "Hrystyna Kulyavych",
    category: "family",
    image: "../../../images/hrystyna-8.jpg",
  },
  {
    id: 18,
    name: "Hrystyna Kulyavych",
    category: "family",
    image: "../../../images/hrystyna-9.jpg",
  },
  {
    id: 19,
    name: "Solomiya Stelmakh",
    category: "portret",
    image: "../../../images/Chicago-1.jpeg",
  },
  {
    id: 20,
    name: "Solomiya Stelmakh",
    category: "portret",
    image: "../../../images/Chicago-2.jpeg",
  },
  {
    id: 21,
    name: "Solomiya Stelmakh",
    category: "portret",
    image: "../../../images/Chicago-3.jpeg",
  },
  {
    id: 22,
    name: "Solomiya Stelmakh",
    category: "portret",
    image: "../../../images/Chicago-4.jpeg",
  },
  {
    id: 23,
    name: "Solomiya Stelmakh",
    category: "portret",
    image: "../../../images/Chicago-5.jpeg",
  },
  {
    id: 24,
    name: "Solomiya Stelmakh",
    category: "portret",
    image: "../../../images/Chicago-6.jpeg",
  },
  {
    id: 25,
    name: "Solomiya Stelmakh",
    category: "portret",
    image: "../../../images/Chicago-7.jpeg",
  },
  {
    id: 26,
    name: "Solomiya Stelmakh",
    category: "portret",
    image: "../../../images/Chicago-8.jpeg",
  },
  {
    id: 27,
    name: "Мис Рока",
    category: "nature",
    image: "../../../images/mus_roka-1.jpeg",
  },
  {
    id: 28,
    name: "Мис Рока",
    category: "nature",
    image: "../../../images/mus_roka-2.jpeg",
  },
  {
    id: 29,
    name: "Мис Рока",
    category: "nature",
    image: "../../../images/mus_roka-3.jpeg",
  },
  {
    id: 30,
    name: "Мис Рока",
    category: "nature",
    image: "../../../images/mus_roka-4.jpeg",
  },
  {
    id: 31,
    name: "Bilinski",
    category: "family",
    image: "../../../images/Bilinski-1.jpeg",
  },
  {
    id: 32,
    name: "Мис Рока",
    category: "nature",
    image: "../../../images/mus_roka-6.jpeg",
  },
  {
    id: 33,
    name: "Мис Рока",
    category: "nature",
    image: "../../../images/mus_roka-7.jpeg",
  },
  {
    id: 34,
    name: "Мис Рока",
    category: "nature",
    image: "../../../images/mus_roka-8.jpeg",
  },
  {
    id: 35,
    name: "Orest Rubel",
    category: "portret",
    image: "../../../images/orest-1.jpg",
  },
  {
    id: 36,
    name: "Orest Rubel",
    category: "portret",
    image: "../../../images/orest-2.jpg",
  },
  {
    id: 37,
    name: "Orest Rubel",
    category: "portret",
    image: "../../../images/orest-3.jpg",
  },
  {
    id: 38,
    name: "Orest Rubel",
    category: "portret",
    image: "../../../images/orest-4.jpg",
  },
  {
    id: 39,
    name: "Orest Rubel",
    category: "portret",
    image: "../../../images/orest-5.jpg",
  },
  {
    id: 40,
    name: "Bilinski",
    category: "family",
    image: "../../../images/Bilinski-2.jpeg",
  },
  {
    id: 41,
    name: "Bilinski",
    category: "portret",
    image: "../../../images/Bilinski-3.jpeg",
  },
  {
    id: 42,
    name: "Bilinski",
    category: "family",
    image: "../../../images/Bilinski-4.jpeg",
  },
  {
    id: 43,
    name: "Bilinski",
    category: "family",
    image: "../../../images/Bilinski-5.jpeg",
  },
  {
    id: 44,
    name: "Bilinski",
    category: "family",
    image: "../../../images/Bilinski-6.jpeg",
  },
];
export default cardArray;
